name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        env:
          REPO_DIR: ""
        run: |
          export REPO_DIR=$(echo ${GITHUB_REPOSITORY} | cut -d "/" -f2)
          git clone https://github.com/${GITHUB_REPOSITORY}.git --branch main --depth 1
          cd ${REPO_DIR}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          cd ${REPO_DIR}
          npm run build

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./dist
          git init
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master:gh-pages
